require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaskJournalsController do

  # This should return the minimal set of attributes required to create a valid
  # TaskJournal. As you add validations to TaskJournal, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "time_entry_hours" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaskJournalsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all task_journals as @task_journals" do
      task_journal = TaskJournal.create! valid_attributes
      get :index, {}, valid_session
      assigns(:task_journals).should eq([task_journal])
    end
  end

  describe "GET show" do
    it "assigns the requested task_journal as @task_journal" do
      task_journal = TaskJournal.create! valid_attributes
      get :show, {:id => task_journal.to_param}, valid_session
      assigns(:task_journal).should eq(task_journal)
    end
  end

  describe "GET new" do
    it "assigns a new task_journal as @task_journal" do
      get :new, {}, valid_session
      assigns(:task_journal).should be_a_new(TaskJournal)
    end
  end

  describe "GET edit" do
    it "assigns the requested task_journal as @task_journal" do
      task_journal = TaskJournal.create! valid_attributes
      get :edit, {:id => task_journal.to_param}, valid_session
      assigns(:task_journal).should eq(task_journal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TaskJournal" do
        expect {
          post :create, {:task_journal => valid_attributes}, valid_session
        }.to change(TaskJournal, :count).by(1)
      end

      it "assigns a newly created task_journal as @task_journal" do
        post :create, {:task_journal => valid_attributes}, valid_session
        assigns(:task_journal).should be_a(TaskJournal)
        assigns(:task_journal).should be_persisted
      end

      it "redirects to the created task_journal" do
        post :create, {:task_journal => valid_attributes}, valid_session
        response.should redirect_to(TaskJournal.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved task_journal as @task_journal" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaskJournal.any_instance.stub(:save).and_return(false)
        post :create, {:task_journal => { "time_entry_hours" => "invalid value" }}, valid_session
        assigns(:task_journal).should be_a_new(TaskJournal)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaskJournal.any_instance.stub(:save).and_return(false)
        post :create, {:task_journal => { "time_entry_hours" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested task_journal" do
        task_journal = TaskJournal.create! valid_attributes
        # Assuming there are no other task_journals in the database, this
        # specifies that the TaskJournal created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TaskJournal.any_instance.should_receive(:update).with({ "time_entry_hours" => "1" })
        put :update, {:id => task_journal.to_param, :task_journal => { "time_entry_hours" => "1" }}, valid_session
      end

      it "assigns the requested task_journal as @task_journal" do
        task_journal = TaskJournal.create! valid_attributes
        put :update, {:id => task_journal.to_param, :task_journal => valid_attributes}, valid_session
        assigns(:task_journal).should eq(task_journal)
      end

      it "redirects to the task_journal" do
        task_journal = TaskJournal.create! valid_attributes
        put :update, {:id => task_journal.to_param, :task_journal => valid_attributes}, valid_session
        response.should redirect_to(task_journal)
      end
    end

    describe "with invalid params" do
      it "assigns the task_journal as @task_journal" do
        task_journal = TaskJournal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaskJournal.any_instance.stub(:save).and_return(false)
        put :update, {:id => task_journal.to_param, :task_journal => { "time_entry_hours" => "invalid value" }}, valid_session
        assigns(:task_journal).should eq(task_journal)
      end

      it "re-renders the 'edit' template" do
        task_journal = TaskJournal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaskJournal.any_instance.stub(:save).and_return(false)
        put :update, {:id => task_journal.to_param, :task_journal => { "time_entry_hours" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested task_journal" do
      task_journal = TaskJournal.create! valid_attributes
      expect {
        delete :destroy, {:id => task_journal.to_param}, valid_session
      }.to change(TaskJournal, :count).by(-1)
    end

    it "redirects to the task_journals list" do
      task_journal = TaskJournal.create! valid_attributes
      delete :destroy, {:id => task_journal.to_param}, valid_session
      response.should redirect_to(task_journals_url)
    end
  end

end
